### ISSUE TITLE
hysteria2无法使用用户名密码认证

### ISSUE THREAD

**Issue by xmapst** [daeuniverse/outbound#13]
@mzz2017 [8df8256](https://github.com/daeuniverse/outbound/commit/8df825695cc323e264023431df0efd41677265de)此改动是何用意?  修改完之后只用了用户名进行认证
![image](https://github.com/daeuniverse/outbound/assets/36829716/4e6e28dd-32db-4f88-a24b-e879e41f3bbc)

**Comment by mzz2017** [comment]
User.String() 拿到的是编码后的内容，之前想的是 auth=密码，没想到还有用户名+密码的可能性。

现在看来最好是拿到之后做个 uridecode。

**Comment by xmapst** [comment]
> User.String() 拿到的是编码后的内容，之前想的是 auth=密码，没想到还有用户名+密码的可能性。
> 
> 现在看来最好是拿到之后做个 uridecode。

可以分开拿 使用时候再url.UserPassword
